export const DATA_AVAILABILITY = 'DATA_AVAILABILITY';
export const DATA_RESERVATION = 'DATA_RESERVATION';
export const DATA_RESERVATION_BOOKING_TIME = 'DATA_RESERVATION_BOOKING_TIME';
export const DATA_RESERVATION_CONFIRMED = 'DATA_RESERVATION_CONFIRMED';

export const HANDLE_CREATE_AVAILABILITY = 'HANDLE_CREATE_AVAILABILITY';
export const HANDLE_CREATE_RESERVATION = 'HANDLE_CREATE_RESERVATION';
